# 경로 -> 절대경로로 수정하기

In [8]:
import pandas as pd
import numpy as np

In [40]:
# 
df1 = pd.read_csv('/home/ubuntu/movie/data/movie_code_add_director.csv')
df2 = pd.read_csv('/home/ubuntu/movie/data/naver_movie.csv')
df1 = df1.drop('Unnamed: 0',1)
df1 = df1.drop('Rate',1)
df3 = pd.merge(df1,df2,how='left',on='movieNm')

In [41]:
type(df1['movieNm'][0])

str

In [42]:
df2['movieNm']

0                             군함도
1                            덩케르크
2                           47 미터
3                          슈퍼배드 3
4                      스파이더맨: 홈커밍
5                              플립
6                           택시운전사
7                              옥자
8      극장판 짱구는 못말려 : 습격!! 외계인 덩덩이
9                              리얼
10                           내 사랑
11                          송 투 송
12                             박열
13                          위시 어폰
14                        예수는 역사다
15                     카3: 새로운 도전
16                           청년경찰
17                        너의 이름은.
18                  명탐정 코난:진홍의 연가
19                    킹 아서: 제왕의 검
20                         다크 나이트
21              여자 보험왕 : 그녀의 영업비밀
22                           남한산성
23                     킹스맨: 골든 서클
24                    혹성탈출: 종의 전쟁
25                   오즈: 신기한 마법가루
26                      토르: 라그나로크
27                          브이아이피
28                             시암
29                    애나벨: 인형의 주인
                  ...
900                         애프터매스
901                  사랑과 욕망의 짐노페디
902                            휴가
903              프레셔스 카고 : 프로 범죄단
904                     멀홀랜드 드라이브
905                            마셜
906                          복성고조
907                   더 킹 오브 엠파이어
908             소드 마스터: 절대 강호의 죽음
909                         샌드 캐슬
910                    내 친구의 아내 2
911                            정글
912                 쥬라기 월드: 폴른 킹덤
913              로만 J 이스라엘, 에스콰이어
914                          죽음의집
915                          디나이얼
916                         더 리투얼
917                          바보계획
918                         골든 타임
919                     아기배달부 스토크
920                           ARQ
921                 첩보원: 독일군 잠입작전
922                        닌자의 나라
923                            모건
924                           베테랑
925                무림강호: 영웅불패의 신화
926                서유기3: 월광보합 리턴즈
927                        더 프로미스
928                     더 쉐도우 이펙트
929                       400 데이즈
Name: movieNm, Length: 930, dtype: object

In [43]:
df3

,director,movieCd,movieNm,naver_movieCd,ntz_see_score,spc_score,ntz_score
0,연상호,20168323,염력,153651.0,0.0,0.0,0.0
1,최성현,20176104,그것만이 내 세상,158180.0,0.0,0.0,0.0
2,애덤 로비텔,20178126,인시디어스4: 라스트 키,158647.0,0.0,0.0,0.0
3,리 언크리치,20179985,코코,151728.0,0.0,0.0,0.0
4,김용화,20150976,신과함께-죄와 벌,85579.0,0.0,0.0,0.0
5,웨스 볼,20175054,메이즈 러너: 데스 큐어,149248.0,0.0,0.0,0.0
6,니콜라이 퓰시,20178395,12 솔져스,168037.0,0.0,0.0,0.0
7,장준환,20170590,1987,158191.0,0.0,0.0,0.0
8,노엘 클리어리,20179228,마야2,172009.0,0.0,0.0,0.0
9,김석윤,20179205,조선명탐정: 흡혈괴마의 비밀,165748.0,0.0,0.0,0.0
10,리들리 스콧,20178469,올 더 머니,163842.0,0.0,0.0,0.0
11,제임스 카메론,19980074,타이타닉,18847.0,0.0,0.0,0.0
12,마틴 캠벨,20189901,더 포리너,165791.0,0.0,0.0,0.0
13,폴 킹,20178672,패딩턴 2,146489.0,0.0,0.0,0.0
14,홍헌표,20189761,터닝메카드W: 반다인의 비밀 특별판,NaN,NaN,NaN,NaN
15,임순례,20170841,리틀 포레스트,154449.0,0.0,0.0,0.0
16,라이언 쿠글러,20170561,블랙 팬서,137326.0,0.0,0.0,0.0
17,노동석,20168250,골든슬럼버,158112.0,0.0,0.0,0.0
18,조근현,20176121,흥부: 글로 세상을 바꾼 자,NaN,NaN,NaN,NaN
19,야마모토 야스이치로,20078561,명탐정 코난:감벽의 관,NaN,NaN,NaN,NaN
20,마이클 그레이시,20179462,위대한 쇼맨,106360.0,0.0,0.0,0.0
21,변성현,20164844,불한당: 나쁜 놈들의 세상,154112.0,0.0,0.0,0.0
22,토미 위르콜라,20177946,월요일이 사라졌다,118955.0,0.0,0.0,0.0
23,제임스 폴리,20180542,50가지 그림자: 해방,154598.0,0.0,0.0,0.0
24,기예르모 델 토로,20173436,셰이프 오브 워터: 사랑의 모양,158626.0,0.0,0.0,0.0
25,등위봉,20189882,반딧불이 딘딘,171767.0,0.0,0.0,0.0
26,홍창표,20150969,궁합,141206.0,0.0,0.0,0.0
27,히로키 류이치,20179731,나미야 잡화점의 기적,159862.0,0.0,0.0,0.0
28,프란시스 로렌스,20180341,레드 스패로,151744.0,0.0,0.0,0.0
29,스티븐 스필버그,20189861,더 포스트,159848.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
294,제임스 폴리,20161141,50가지 그림자: 심연,144081.0,0.0,0.0,0.0
295,장예모,20163580,그레이트 월,126034.0,0.0,0.0,0.0
296,고어 버빈스키,20167362,더 큐어,143372.0,0.0,0.0,0.0
297,마대윤,20161366,"그래, 가족",151192.0,0.0,0.0,0.0
298,알베르토 로드리게즈,20167906,마이펫 오지,157500.0,0.0,0.0,0.0
299,이주영,20161723,싱글라이더,146459.0,0.0,0.0,0.0
300,김준성,20156562,루시드 드림,130713.0,0.0,0.0,0.0
301,멜 깁슨,20167922,핵소 고지,142305.0,0.0,0.0,0.0
302,조의석,20161725,마스터,145162.0,0.0,0.0,0.0
303,가렛 에드워즈,20163183,로그 원: 스타워즈 스토리,136868.0,0.0,0.0,0.0
304,가스 제닝스,20162025,씽,144938.0,0.0,0.0,0.0
305,박정우,20144641,판도라,132933.0,0.0,0.0,0.0
306,유야마 쿠니히코,20162727,루돌프와 많이있어,153951.0,0.0,0.0,0.0
307,유야마 쿠니히코,20162183,포켓몬 더 무비 XY&Z 「볼케니온 : 기계왕국의 비밀」,NaN,NaN,NaN,NaN
308,홍지영,20152371,"당신, 거기 있어줄래요",145292.0,0.0,0.0,0.0
309,야쿠와 신노스케,20165285,극장판 도라에몽: 신 진구의 버스 오브 재팬,NaN,NaN,NaN,NaN
310,롭 라이너,19890291,해리가 샐리를 만났을 때,10250.0,0.0,0.0,0.0
311,켄 로치,20161763,"나, 다니엘 블레이크",150376.0,0.0,0.0,0.0
312,김진혁,20163014,7년-그들이 없는 언론,146526.0,0.0,0.0,0.0
313,모튼 틸덤,20161084,패신저스,116233.0,0.0,0.0,0.0
314,주지홍,20150966,사랑하기 때문에,140010.0,0.0,0.0,0.0
315,알렉세이 트시칠린,20165153,눈의 여왕 3: 눈과 불의 마법대결,NaN,NaN,NaN,NaN
316,김태용,20151181,여교사,139673.0,0.0,0.0,0.0
317,저스틴 커젤,20164421,어쌔신 크리드,118307.0,0.0,0.0,0.0
318,로버트 저메키스,20168381,얼라이드,149777.0,0.0,0.0,0.0
319,피터 잭슨,20168324,반지의 제왕 : 반지원정대 (확장판),NaN,NaN,NaN,NaN
320,피터 잭슨,20168664,반지의 제왕 : 두개의 탑 (확장판),NaN,NaN,NaN,NaN
321,자비에 돌란,20163186,단지 세상의 끝,137958.0,0.0,0.0,0.0
322,피터 잭슨,20168689,반지의 제왕 : 왕의 귀환 (확장판),NaN,NaN,NaN,NaN
323,다라 오코넬,20168366,바다 탐험대 옥토넛 시즌4: 바다 괴물 대소동,158266.0,0.0,0.0,0.0

In [29]:
for i in range(len(df3['ntz_see_score'])):
    if(np.isnan(df3['ntz_see_score'][i])):
        print(str(i)+" NaN")
        name = df3['movieNm'][i].replace(' ','')
        print(name)
        for j in range(len(df2)):
            df2_name = df2['movieNm'][j].replace(' ','')
            print(df2_name)
            if(df2_name[0:8] == name[0:8]):
                df3['naver_movieCd'][i] = df2['naver_movieCd'][j]
                df3['ntz_see_score'][i] = df2['ntz_see_score'][j]
                df3['spc_score'][i] = df2['spc_score'][j]
                df3['ntz_score'][i] = df2['ntz_score'][j]
                if(df2_name[0:6] == name[0:6]):
                    df3['naver_movieCd'][i] = df2['naver_movieCd'][j]
                    df3['ntz_see_score'][i] = df2['ntz_see_score'][j]
                    df3['spc_score'][i] = df2['spc_score'][j]
                    df3['ntz_score'][i] = df2['ntz_score'][j]
                    if(df2_name[0:4] == name[0:4]):     
                        df3['naver_movieCd'][i] = df2['naver_movieCd'][j]
                        df3['ntz_see_score'][i] = df2['ntz_see_score'][j]
                        df3['spc_score'][i] = df2['spc_score'][j]
                        df3['ntz_score'][i] = df2['ntz_score'][j]            
    elif(np.isnan(df3['naver_movieCd'][i])):
        df3['naver_movieCd'][i] = 0
        df3['ntz_see_score'][i] = 0
        df3['spc_score'][i] = 0
        df3['ntz_score'][i] = 0

In [30]:
df3 = df3.dropna()
df3 = df3.reset_index(drop=True)
df3

,director,movieCd,movieNm,naver_movieCd,ntz_see_score,spc_score,ntz_score
0,최성현,20176104,그것만이 내 세상,158180.0,9.17,5.20,8.91
1,리 언크리치,20179985,코코,151728.0,9.20,8.00,9.25
2,김용화,20150976,신과함께-죄와 벌,85579.0,8.73,5.92,7.84
3,장준환,20170590,1987,158191.0,9.31,8.08,9.24
4,김석윤,20179205,조선명탐정: 흡혈괴마의 비밀,165748.0,7.52,5.17,6.63
5,폴 킹,20178672,패딩턴 2,146489.0,9.13,7.67,9.12
6,임순례,20170841,리틀 포레스트,154449.0,9.01,6.36,8.76
7,라이언 쿠글러,20170561,블랙 팬서,137326.0,8.33,6.67,7.51
8,노동석,20168250,골든슬럼버,158112.0,6.29,5.00,5.25
9,야마모토 야스이치로,20078561,명탐정 코난:감벽의 관,66725.0,8.59,5.00,8.42
10,마이클 그레이시,20179462,위대한 쇼맨,106360.0,9.29,6.60,9.38
11,토미 위르콜라,20177946,월요일이 사라졌다,118955.0,8.50,5.25,8.32
12,제임스 폴리,20180542,50가지 그림자: 해방,154598.0,8.37,2.67,7.95
13,기예르모 델 토로,20173436,셰이프 오브 워터: 사랑의 모양,158626.0,8.68,8.18,8.36
14,등위봉,20189882,반딧불이 딘딘,171767.0,7.78,6.00,7.90
15,홍창표,20150969,궁합,141206.0,7.49,4.00,6.48
16,히로키 류이치,20179731,나미야 잡화점의 기적,159862.0,7.66,5.75,7.34
17,프란시스 로렌스,20180341,레드 스패로,151744.0,8.54,5.33,8.55
18,스티븐 스필버그,20189861,더 포스트,159848.0,8.81,7.63,8.76
19,신재호,20189663,게이트,172005.0,9.05,3.00,3.65
20,스티븐 크보스키,20176947,원더,151196.0,9.43,6.86,9.42
21,홍기선,20168161,1급기밀,149504.0,8.86,5.86,8.86
22,장창원,20165748,꾼,152385.0,8.32,4.40,7.63
23,장항준,20173581,기억의 밤,160399.0,8.41,5.67,8.16
24,제임스 폴리,20161141,50가지 그림자: 심연,144081.0,7.77,2.25,7.42

In [ ]:
df3.to_csv('/home/ubuntu/movie/data/naver_movie_all.csv',index=False)